# Generated by Django 4.1.1 on 2022-09-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=models.ImageField(
                blank=True, default="placeholder.png", null=True, upload_to="images"
            ),
        ),
    ]
